/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/Background_test_230427.gltf
*/

import React, { useRef } from "react";
import { useAnimations, useGLTF } from "@react-three/drei";

export default function CityTest(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/Background_test_230427.gltf"
  );
  const { actions, names } = useAnimations(animations, group);
  console.log(actions);

  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 0.09, 0]}>
        <mesh
          geometry={nodes.pCube9.geometry}
          material={materials.lambert7}
          position={[-111.78, 0.18, -82.29]}
          scale={[4, 0.35, 4]}
        />
        <mesh
          geometry={nodes.pCube10.geometry}
          material={materials.lambert3}
          position={[3.7, 0.23, -66.97]}
          rotation={[0, -0.15, 0]}
          scale={[10, 0.3, 10]}
        />
        <mesh
          geometry={nodes.pCube11.geometry}
          material={materials.lambert3}
          position={[58.99, 0.14, -58.04]}
          rotation={[0, -0.45, 0]}
          scale={[3, 0.3, 3]}
        />
        <mesh
          geometry={nodes.pCube14.geometry}
          material={materials.lambert1}
          position={[-73.06, 0.18, -18.42]}
          scale={[6, 0.3, 6]}
        />
        <mesh
          geometry={nodes.pCylinder3.geometry}
          material={materials.lambert1}
          position={[-24.88, 0.49, -23.88]}
          scale={[19, 0.3, 19]}
        />
        <mesh
          geometry={nodes.pCube15.geometry}
          material={materials.lambert1}
          position={[-70, 0.18, -8.91]}
          scale={[6, 0.3, 6]}
        />
        <mesh
          geometry={nodes.pCube16.geometry}
          material={materials.lambert1}
          position={[1.19, 0.19, 12.56]}
          scale={[5, 0.36, 5]}
        />
        <mesh
          geometry={nodes.pCube17.geometry}
          material={materials.lambert1}
          position={[-1.55, 0.2, -24.76]}
          scale={[5, 0.35, 5]}
        />
        <mesh
          geometry={nodes.pCube18.geometry}
          material={materials.lambert1}
          position={[25.13, 0.19, -16.9]}
          scale={[5, 0.35, 5]}
        />
        <mesh
          geometry={nodes.pCube20.geometry}
          material={materials.lambert1}
          position={[-103.36, 0.22, 29.72]}
          rotation={[0, -0.36, 0]}
          scale={[10.44, 0.35, 7]}
        />
        <mesh
          geometry={nodes.pCube21.geometry}
          material={materials.lambert1}
          position={[-70.28, 0.17, 3.54]}
          rotation={[0, -0.93, 0]}
          scale={[7, 0.35, 7]}
        />
        <mesh
          geometry={nodes.pCube22.geometry}
          material={materials.lambert1}
          position={[-23.1, 0.2, 45.5]}
          scale={[5, 0.35, 5]}
        />
        <mesh
          geometry={nodes.polySurface2.geometry}
          material={materials.lambert3}
          position={[-98.5, 0.19, -52.53]}
          scale={[5, 0.35, 5]}
        />
        <mesh
          geometry={nodes.polySurface1.geometry}
          material={materials.lambert3}
          position={[-98.5, 0.19, -52.53]}
          scale={[5, 0.35, 5]}
        />
        <mesh
          geometry={nodes.polySurface4.geometry}
          material={materials.lambert3}
          position={[-131.62, 0.14, -17.54]}
          scale={[5, 0.3, 5]}
        />
        <mesh
          geometry={nodes.polySurface3.geometry}
          material={materials.lambert3}
          position={[-131.62, 0.14, -17.54]}
          scale={[5, 0.3, 5]}
        />
        <mesh
          geometry={nodes.pCube23.geometry}
          material={materials.lambert1}
          position={[11.42, 0.19, 23.39]}
          scale={[5, 0.35, 5]}
        />
        <mesh
          geometry={nodes.pCube25.geometry}
          material={materials.lambert1}
          position={[68.74, 0.17, 2.52]}
          scale={[5, 0.35, 5]}
        />
        <mesh
          geometry={nodes.polySurface5.geometry}
          material={materials.lambert3}
          position={[58.34, 0.18, 20.45]}
          scale={[6, 0.35, 5]}
        />
        <mesh
          geometry={nodes.polySurface6.geometry}
          material={materials.lambert1}
          position={[58.34, 0.18, 20.45]}
          scale={[6, 0.35, 5]}
        />
        <mesh
          geometry={nodes.pCube26.geometry}
          material={materials.lambert1}
          position={[112.05, 0.19, 20.73]}
          scale={[4, 0.35, 4]}
        />
        <mesh
          geometry={nodes.pCube27.geometry}
          material={materials.lambert1}
          position={[112.53, 0.18, 13.48]}
          scale={[5, 0.35, 5]}
        />
        <mesh
          geometry={nodes.pCube28.geometry}
          material={materials.lambert1}
          position={[45.6, 0.18, -14.12]}
          scale={[5, 0.35, 5]}
        />
        <mesh
          geometry={nodes.pCube29.geometry}
          material={materials.lambert1}
          position={[104.53, 0.17, -47.09]}
          rotation={[0, -1.14, 0]}
          scale={[3, 0.35, 3]}
        />
        <mesh
          geometry={nodes.pCube30.geometry}
          material={materials.lambert1}
          position={[132.23, 0.18, -50.82]}
          scale={[5, 0.35, 5]}
        />
        <mesh
          geometry={nodes.pCube31.geometry}
          material={materials.lambert1}
          position={[92.85, 0.17, -41.33]}
          scale={[5, 0.35, 5]}
        />
        <mesh
          geometry={nodes.pCube32.geometry}
          material={materials.lambert1}
          position={[123.98, 0.16, -30.46]}
          scale={[5, 0.35, 5]}
        />
        <mesh
          geometry={nodes.pCube33.geometry}
          material={materials.lambert1}
          position={[146.97, 0.18, -1.26]}
          rotation={[0, 0.77, 0]}
          scale={[5, 0.35, 5]}
        />
        <mesh
          geometry={nodes.pCube34.geometry}
          material={materials.lambert1}
          position={[89.25, 0.17, -14.12]}
          scale={[5, 0.35, 5]}
        />
        <mesh geometry={nodes.pCube39.geometry} material={materials.lambert1} />
        <mesh
          geometry={nodes.pCube40.geometry}
          material={materials.lambert1}
          position={[-73.45, 0.21, 98.99]}
          rotation={[0, -0.61, 0]}
          scale={[5, 0.35, 5]}
        />
        <mesh
          geometry={nodes.pCube41.geometry}
          material={materials.lambert1}
          position={[-119.34, 0.18, 56.52]}
          scale={[5, 0.35, 5]}
        />
        <mesh
          geometry={nodes.pCube42.geometry}
          material={materials.lambert1}
          position={[-51.5, 0.18, 71.76]}
          scale={[5, 0.35, 5]}
        />
        <mesh
          geometry={nodes.pCube43.geometry}
          material={materials.lambert1}
          position={[149.31, 0.18, 11.6]}
          rotation={[0, 0.52, 0]}
          scale={[6, 0.35, 6]}
        />
        <mesh
          geometry={nodes.pCube44.geometry}
          material={materials.lambert1}
          position={[162.57, 0.18, 2.58]}
          rotation={[0, 0.56, 0]}
          scale={[5, 0.35, 5]}
        />
        <mesh
          geometry={nodes.pCube45.geometry}
          material={materials.lambert1}
          position={[153.52, 0.18, 24.13]}
          rotation={[0, 0.18, 0]}
          scale={[5, 0.35, 5]}
        />
        <mesh
          geometry={nodes.pCube46.geometry}
          material={materials.lambert1}
          position={[208.53, 0.17, 34.97]}
          rotation={[0, 0.58, 0]}
          scale={[5, 0.35, 5]}
        />
        <mesh
          geometry={nodes.pCube47.geometry}
          material={materials.lambert1}
          position={[216.01, 0.17, 67.3]}
          rotation={[0, -0.47, 0]}
          scale={[5, 0.35, 5]}
        />
        <mesh
          geometry={nodes.pCube48.geometry}
          material={materials.lambert1}
          position={[230.04, 0.17, 66.14]}
          rotation={[0, -0.24, 0]}
          scale={[5, 0.35, 5]}
        />
        <mesh
          geometry={nodes.pCube49.geometry}
          material={materials.lambert1}
          position={[258.5, 0.17, 61.76]}
          rotation={[0, 0.41, 0]}
          scale={[3, 0.35, 3]}
        />
        <mesh
          geometry={nodes.pCube50.geometry}
          material={materials.lambert1}
          position={[235.67, 0.18, 81.9]}
          rotation={[0, -0.16, 0]}
          scale={[3, 0.35, 3]}
        />
        <mesh
          geometry={nodes.pCube51.geometry}
          material={materials.lambert1}
          position={[226.84, 0.17, 119]}
          rotation={[0, 0.46, 0]}
          scale={[5, 0.35, 5]}
        />
        <mesh
          geometry={nodes.pCube52.geometry}
          material={materials.lambert1}
          position={[226.03, 0.18, 157.09]}
          scale={[5, 0.35, 5]}
        />
        <mesh
          geometry={nodes.pCylinder8.geometry}
          material={materials.lambert7}
          position={[-163.58, 0.33, -35.35]}
          scale={[17.09, 0.32, 17.09]}
        />
        <mesh
          geometry={nodes.pCube53.geometry}
          material={materials.lambert7}
          position={[-147.87, 0.18, -52.93]}
          rotation={[0, 0.92, 0]}
          scale={[5, 0.35, 5]}
        />
        <mesh
          geometry={nodes.pCube54.geometry}
          material={materials.lambert7}
          position={[-174.11, 0.18, -54.09]}
          rotation={[0, 0.47, 0]}
          scale={[5, 0.35, 5]}
        />
        <mesh
          geometry={nodes.pCube55.geometry}
          material={materials.lambert1}
          position={[-140.1, 0.15, -27.76]}
          scale={[5, 0.35, 5]}
        />
        <mesh
          geometry={nodes.pCube56.geometry}
          material={materials.lambert1}
          position={[-146.05, 0.17, -3.52]}
          rotation={[0, 0.3, 0]}
          scale={[5, 0.35, 5]}
        />
        <mesh
          geometry={nodes.pCube57.geometry}
          material={materials.lambert1}
          position={[-158.43, 0.18, -1.8]}
          rotation={[0, -0.71, 0]}
          scale={[6, 0.35, 6]}
        />
        <mesh
          geometry={nodes.pCube58.geometry}
          material={materials.lambert1}
          position={[-180.68, 0.21, -50.89]}
          rotation={[-0.01, 0.43, 0.05]}
          scale={[5, 0.35, 5]}
        />
        <mesh
          geometry={nodes.pCube59.geometry}
          material={materials.lambert1}
          position={[-210.25, 0.17, -79.16]}
          rotation={[0, 0.24, 0]}
          scale={[5, 0.35, 5]}
        />
        <mesh
          geometry={nodes.pCube60.geometry}
          material={materials.lambert1}
          position={[-220.2, 0.18, -76.94]}
          rotation={[0, 0.31, 0]}
          scale={[5, 0.35, 5]}
        />
        <mesh
          geometry={nodes.pCube61.geometry}
          material={materials.lambert1}
          position={[-173.19, 0.18, -83.4]}
          scale={[5, 0.35, 5]}
        />
        <mesh
          geometry={nodes.pCube62.geometry}
          material={materials.lambert1}
          position={[-146.33, 0.18, -80.42]}
          rotation={[0, -0.4, 0]}
          scale={[5, 0.35, 5]}
        />
      </group>
      <group position={[-0.79, 0, -1.37]}>
        <mesh
          geometry={nodes.pCube161.geometry}
          material={materials.lambert7}
          position={[-6.96, -1.73, -11.29]}
        />
        <mesh
          geometry={nodes.pCube160.geometry}
          material={materials.lambert1}
          position={[-0.98, -0.73, -8.17]}
          rotation={[0, 0.52, 0]}
          scale={[1, 1, 2.26]}
        />
        <mesh
          geometry={nodes.pCube162.geometry}
          material={materials.lambert1}
          position={[-6.56, -0.73, -5.02]}
          rotation={[0, 0.52, 0]}
          scale={[1, 1, 2.26]}
        />
        <mesh
          geometry={nodes.pCube163.geometry}
          material={materials.lambert7}
          position={[-12.54, -1.73, -8.14]}
        />
        <mesh
          geometry={nodes.pCube159.geometry}
          material={materials.lambert7}
          position={[-10.99, -1.73, -5.44]}
        />
        <mesh
          geometry={nodes.pCube158.geometry}
          material={materials.lambert1}
          position={[-5.01, -0.73, -2.32]}
          rotation={[0, 0.52, 0]}
          scale={[1, 1, 2.26]}
        />
        <mesh
          geometry={nodes.pCube157.geometry}
          material={materials.lambert7}
          position={[-5.42, -1.73, -8.58]}
        />
        <mesh
          geometry={nodes.pCube156.geometry}
          material={materials.lambert1}
          position={[0.57, -0.73, -5.46]}
          rotation={[0, 0.52, 0]}
          scale={[1, 1, 2.26]}
        />
        <mesh
          geometry={nodes.pCube139.geometry}
          material={materials.lambert1}
          position={[-0.67, -0.73, 5.23]}
          rotation={[0, 0.52, 0]}
          scale={[1, 1, 2.26]}
        />
        <mesh
          geometry={nodes.pCube153.geometry}
          material={materials.lambert7}
          position={[-6.65, -1.73, 2.11]}
        />
        <mesh
          geometry={nodes.pCube154.geometry}
          material={materials.lambert1}
          position={[4.91, -0.73, 2.09]}
          rotation={[0, 0.52, 0]}
          scale={[1, 1, 2.26]}
        />
        <mesh
          geometry={nodes.pCube155.geometry}
          material={materials.lambert7}
          position={[-1.08, -1.73, -1.03]}
        />
        <mesh
          geometry={nodes.pCube164.geometry}
          material={materials.lambert1}
          position={[6.56, -0.73, 5.02]}
          rotation={[0, 0.52, 0]}
          scale={[1, 1, 2.26]}
        />
        <mesh
          geometry={nodes.pCube165.geometry}
          material={materials.lambert7}
          position={[0.57, -1.73, 1.9]}
        />
        <mesh
          geometry={nodes.pCube166.geometry}
          material={materials.lambert1}
          position={[0.98, -0.73, 8.17]}
          rotation={[0, 0.52, 0]}
          scale={[1, 1, 2.26]}
        />
        <mesh
          geometry={nodes.pCube167.geometry}
          material={materials.lambert7}
          position={[-5, -1.73, 5.05]}
        />
      </group>
      <line
        geometry={nodes.Line001.geometry}
        material={nodes.Line001.material}
        position={[-27.75, 3.36, -41.82]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.pCube177.geometry}
        material={materials.lambert7}
        position={[-140.84, 20.51, -80.65]}
        rotation={[0, -0.69, 0]}
      />
      <mesh
        geometry={nodes.pCylinder4.geometry}
        material={materials.lambert1}
        position={[18.77, 3.36, 7.09]}
        rotation={[1.56, -0.01, 0.82]}
        scale={2.05}
      />
      <mesh
        geometry={nodes.pPlane10.geometry}
        material={materials.lambert6}
        scale={1000}
      />
      <mesh
        geometry={nodes.pPlane9.geometry}
        material={materials.lambert4}
        position={[17.43, 0.1, 34.99]}
        scale={3}
      />
      <group
        position={[-46.24, 3.1, -1.59]}
        rotation={[0, 0.53, 0]}
        scale={[5.35, 5.35, 18.72]}
      >
        <mesh geometry={nodes.mesh_74.geometry} material={materials.lambert7} />
        <mesh
          geometry={nodes.mesh_74_1.geometry}
          material={materials.lambert8}
        />
      </group>
      <group
        position={[-58, 2.74, -1.25]}
        rotation={[0, 0.53, 0]}
        scale={[5.35, 4.64, 18.72]}
      >
        <mesh geometry={nodes.mesh_75.geometry} material={materials.lambert7} />
        <mesh
          geometry={nodes.mesh_75_1.geometry}
          material={materials.lambert8}
        />
      </group>
      <mesh
        geometry={nodes.pCube65.geometry}
        material={materials.lambert7}
        position={[20.5, 3.92, -64.62]}
        rotation={[0, -0.19, 0]}
        scale={[17.44, 7, 7]}
      />
      <mesh
        geometry={nodes.pCube66.geometry}
        material={materials.lambert7}
        position={[15.91, 9.94, -65.5]}
        rotation={[0, -0.19, 0]}
        scale={[8.05, 5, 6.95]}
      />
      <mesh
        geometry={nodes.pCube67.geometry}
        material={materials.lambert7}
        position={[7.94, 4.48, -66.81]}
        rotation={[0, -0.19, 0]}
        scale={8}
      />
      <mesh
        geometry={nodes.pCube68.geometry}
        material={materials.lambert7}
        position={[32.72, 4.47, -61.76]}
        rotation={[0, -0.21, 0]}
        scale={8}
      />
      <mesh
        geometry={nodes.pCube69.geometry}
        material={materials.lambert7}
        position={[7.93, 0, -58.86]}
        rotation={[0, -0.21, 0]}
        scale={5}
      />
      <mesh
        geometry={nodes.pCube70.geometry}
        material={materials.lambert7}
        position={[12.49, 2.97, -56.19]}
        rotation={[0, -0.21, 0]}
        scale={5}
      />
      <mesh
        geometry={nodes.pCube71.geometry}
        material={materials.lambert1}
        position={[31.85, 4.81, -60.69]}
        rotation={[0, -0.23, 0]}
        scale={[1, 0.11, 1]}
      />
      <mesh
        geometry={nodes.pCube72.geometry}
        material={materials.lambert1}
        position={[33.16, 4.81, -60.38]}
        rotation={[0, -0.23, 0]}
        scale={[1, 0.11, 1]}
      />
      <mesh
        geometry={nodes.pCube73.geometry}
        material={materials.lambert1}
        position={[34.47, 4.81, -60.08]}
        rotation={[0, -0.23, 0]}
        scale={[1, 0.11, 1]}
      />
      <mesh
        geometry={nodes.pCube74.geometry}
        material={materials.lambert1}
        position={[35.78, 4.81, -59.77]}
        rotation={[0, -0.23, 0]}
        scale={[1, 0.11, 1]}
      />
      <mesh
        geometry={nodes.pCube75.geometry}
        material={materials.lambert1}
        position={[37.09, 4.81, -59.47]}
        rotation={[0, -0.23, 0]}
        scale={[1, 0.11, 1]}
      />
      <mesh
        geometry={nodes.pCube76.geometry}
        material={materials.lambert1}
        position={[38.39, 4.81, -59.17]}
        rotation={[0, -0.23, 0]}
        scale={[1, 0.11, 1]}
      />
      <mesh
        geometry={nodes.pCube77.geometry}
        material={materials.lambert1}
        position={[39.7, 4.81, -58.86]}
        rotation={[0, -0.23, 0]}
        scale={[1, 0.11, 1]}
      />
      <mesh
        geometry={nodes.pCube81.geometry}
        material={materials.lambert7}
        position={[5.54, 0.97, -51.85]}
        rotation={[0, -0.19, 0]}
        scale={[6.77, 1, 5.02]}
      />
      <mesh
        geometry={nodes.pCube82.geometry}
        material={materials.lambert7}
        position={[-7.39, 0.97, -58.86]}
        rotation={[0, -0.2, 0]}
        scale={[22.01, 1, 11.24]}
      />
      <mesh
        geometry={nodes.pCube83.geometry}
        material={materials.lambert7}
        position={[4.61, 4.61, -48.12]}
        rotation={[0, -0.2, 0]}
        scale={[6.16, 0.4, 2.65]}
      />
      <mesh
        geometry={nodes.pCube84.geometry}
        material={materials.lambert7}
        position={[6.74, 4.16, -43.22]}
        rotation={[0, -0.18, 0]}
        scale={0.5}
      />
      <mesh
        geometry={nodes.pCube85.geometry}
        material={materials.lambert7}
        position={[1.08, 4.16, -44.26]}
        rotation={[0, -0.18, 0]}
        scale={0.5}
      />
      <mesh
        geometry={nodes.pCube86.geometry}
        material={materials.lambert7}
        position={[12.27, 3.3, -46.6]}
        rotation={[0, -0.19, 0]}
        scale={[6.71, 0.35, 1.34]}
      />
      <mesh
        geometry={nodes.pCube87.geometry}
        material={materials.lambert7}
        position={[-4.1, 2.96, -70.61]}
        rotation={[0, -0.19, 0]}
        scale={5}
      />
      <mesh
        geometry={nodes.pCube88.geometry}
        material={materials.lambert7}
        position={[-12.01, 5.48, -69.42]}
        rotation={[0, -0.18, 0]}
        scale={10}
      />
      <group
        position={[-12.71, 8.03, -63.39]}
        rotation={[0, -0.2, 0]}
        scale={[6.34, 4, 4]}
      >
        <mesh geometry={nodes.mesh_98.geometry} material={materials.lambert7} />
        <mesh geometry={nodes.mesh_98_1.geometry} material={materials.blinn1} />
      </group>
      <mesh
        geometry={nodes.pCube90.geometry}
        material={materials.lambert7}
        position={[-16.96, 6.51, -60.92]}
        rotation={[0, -0.2, 0]}
        scale={[1, 1, 5.39]}
      />
      <group
        position={[13.31, 4.33, -57.77]}
        rotation={[0, -0.19, 0]}
        scale={[5.55, 1, 1]}
      >
        <mesh
          geometry={nodes.mesh_100.geometry}
          material={materials.lambert7}
        />
        <mesh
          geometry={nodes.mesh_100_1.geometry}
          material={materials.lambert8}
        />
      </group>
      <mesh
        geometry={nodes.pCube92.geometry}
        material={materials.lambert7}
        position={[6.54, 24.62, -62.72]}
        rotation={[0, -0.18, 0]}
        scale={[8.06, 1, 1]}
      />
      <group
        position={[-23.37, 6.01, -65.65]}
        rotation={[0, -0.18, 0]}
        scale={[1, 1, 1.26]}
      >
        <mesh
          geometry={nodes.mesh_102.geometry}
          material={materials.lambert7}
        />
        <mesh
          geometry={nodes.mesh_102_1.geometry}
          material={materials.lambert3}
        />
      </group>
      <mesh
        geometry={nodes.pCube94.geometry}
        material={materials.lambert1}
        position={[-1.92, 11.73, -54.71]}
        rotation={[0, -0.2, 0]}
      />
      <group
        position={[30.87, 3.16, -15.7]}
        rotation={[0, -0.79, 0]}
        scale={5.4}
      >
        <mesh
          geometry={nodes.mesh_104.geometry}
          material={materials.lambert7}
        />
        <mesh
          geometry={nodes.mesh_104_1.geometry}
          material={materials.lambert8}
        />
      </group>
      <mesh
        geometry={nodes.pCube96.geometry}
        material={materials.lambert7}
        position={[38.29, 3.01, -24.1]}
        rotation={[0, -0.76, 0]}
        scale={[5, 5, 12.77]}
      />
      <mesh
        geometry={nodes.pCube97.geometry}
        material={materials.lambert7}
        position={[26.89, 0.96, -25.38]}
        rotation={[0, -0.75, 0]}
        scale={[1.51, 1, 1]}
      />
      <mesh
        geometry={nodes.pCube98.geometry}
        material={materials.lambert7}
        position={[31.34, 0.96, -21.24]}
        rotation={[0, -0.75, 0]}
        scale={[1.51, 1, 1]}
      />
      <mesh
        geometry={nodes.pCube99.geometry}
        material={materials.lambert1}
        position={[25.32, 0.99, -23.79]}
        rotation={[0, -0.75, 0]}
        scale={[1, 1, 2.26]}
      />
      <mesh
        geometry={nodes.pCube100.geometry}
        material={materials.lambert7}
        position={[23.11, 1.65, -23.29]}
      />
      <mesh
        geometry={nodes.pCube101.geometry}
        material={materials.lambert7}
        position={[23.64, 1.6, -23.83]}
      />
      <mesh
        geometry={nodes.pCube102.geometry}
        material={materials.lambert7}
        position={[24.02, 1.65, -24.23]}
      />
      <mesh
        geometry={nodes.pCube103.geometry}
        material={materials.lambert7}
        position={[23.92, 2.04, -24.12]}
      />
      <mesh
        geometry={nodes.pCube104.geometry}
        material={materials.lambert7}
        position={[23.37, 2.23, -23.73]}
      />
      <mesh
        geometry={nodes.pCube105.geometry}
        material={materials.lambert1}
        position={[29.42, 0.96, -19.84]}
        rotation={[0, -0.75, 0]}
        scale={[1, 1, 2.26]}
      />
      <mesh
        geometry={nodes.pCube106.geometry}
        material={materials.lambert7}
        position={[27.46, 2.23, -19.81]}
      />
      <mesh
        geometry={nodes.pCube107.geometry}
        material={materials.lambert7}
        position={[27.2, 1.65, -19.37]}
      />
      <mesh
        geometry={nodes.pCube108.geometry}
        material={materials.lambert7}
        position={[27.73, 1.6, -19.91]}
      />
      <mesh
        geometry={nodes.pCube109.geometry}
        material={materials.lambert7}
        position={[28.01, 2.04, -20.2]}
      />
      <mesh
        geometry={nodes.pCube110.geometry}
        material={materials.lambert7}
        position={[28.11, 1.65, -20.31]}
      />
      <mesh
        geometry={nodes.pCube111.geometry}
        material={materials.lambert7}
        position={[40.81, 6.19, -27.94]}
        rotation={[0, -0.76, 0]}
      />
      <mesh
        geometry={nodes.pCube112.geometry}
        material={materials.lambert7}
        position={[38.52, 5.76, -27.94]}
        rotation={[0, -0.76, 0]}
        scale={0.5}
      />
      <mesh
        geometry={nodes.pCube113.geometry}
        material={materials.lambert7}
        position={[38.92, 6.01, -26.4]}
        rotation={[0, -0.74, 0]}
      />
      <mesh
        geometry={nodes.pCube114.geometry}
        material={materials.lambert7}
        position={[39.01, 6.01, -26.06]}
        rotation={[0, -0.74, 0]}
      />
      <mesh
        geometry={nodes.pCube131.geometry}
        material={materials.lambert7}
        position={[-0.45, 0, 0.24]}
        rotation={[0, 0.03, 0]}
      />
      <mesh
        geometry={nodes.pCube132.geometry}
        material={materials.lambert7}
        position={[-1.04, 2.72, 2.98]}
        rotation={[0, -1.05, 0]}
        scale={[9.41, 1.01, 10.19]}
      />
      <mesh
        geometry={nodes.pCube133.geometry}
        material={materials.lambert7}
        position={[15.1, 2.72, -6.21]}
        rotation={[0, -1.05, 0]}
        scale={[9.41, 1.01, 10.19]}
      />
      <mesh
        geometry={nodes.pCube134.geometry}
        material={materials.lambert7}
        position={[-1.04, 4.48, 2.98]}
        rotation={[0, -1.05, 0]}
        scale={[9.41, 1.01, 10.19]}
      />
      <mesh
        geometry={nodes.pCube135.geometry}
        material={materials.lambert7}
        position={[15.1, 4.48, -6.21]}
        rotation={[0, -1.05, 0]}
        scale={[9.41, 1.01, 10.19]}
      />
      <mesh
        geometry={nodes.polySurface9.geometry}
        material={materials.lambert7}
      />
      <mesh
        geometry={nodes.pCube168.geometry}
        material={materials.lambert7}
        position={[41.77, 1.61, -38.54]}
        rotation={[0, 0.74, 0]}
        scale={[8, 5, 13.94]}
      />
      <mesh
        geometry={nodes.pCube169.geometry}
        material={materials.lambert7}
        position={[44.48, 4.63, -40.22]}
        rotation={[0, 0.73, 0]}
      />
      <mesh
        geometry={nodes.pCube170.geometry}
        material={materials.lambert7}
        position={[39.85, 23.11, -43.69]}
        rotation={[0, 0.74, 0]}
      />
      <mesh
        geometry={nodes.pCube171.geometry}
        material={materials.lambert7}
        position={[42.41, 23.11, -36.24]}
        rotation={[0, 0.73, 0]}
        scale={[1, 1, 6.3]}
      />
      <mesh
        geometry={nodes.pCube172.geometry}
        material={materials.lambert7}
        position={[44.42, 23.11, -38.05]}
        rotation={[0, 0.73, 0]}
        scale={[1, 1, 6.3]}
      />
      <group position={[69.54, -0.01, -3.13]} rotation={[0, 1.55, 0]}>
        <mesh
          geometry={nodes.mesh_136.geometry}
          material={materials.lambert7}
        />
        <mesh
          geometry={nodes.mesh_136_1.geometry}
          material={materials.blinn1}
        />
      </group>
      <mesh geometry={nodes.mesh_89.geometry} material={materials.lambert7} />
      <mesh geometry={nodes.mesh_89_1.geometry} material={materials.lambert8} />
      <mesh geometry={nodes.mesh_135.geometry} material={materials.lambert7} />
      <mesh geometry={nodes.mesh_135_1.geometry} material={materials.blinn1} />
    </group>
  );
}

useGLTF.preload("/Background_test_230427.gltf");
